# Embedding2Adapter for SLM RAG

Run the cells from top to bottom. Dataset preparation calls Ollama to create embeddings and can take time. The final cell starts HyperNet training.

In [1]:
from collections import Counter
from pathlib import Path
from pprint import pprint
import sys

PROJECT_ROOT = next(
    (path for path in (Path.cwd(), *Path.cwd().parents)
     if (path / "pyproject.toml").exists()),
    None,
)
if PROJECT_ROOT is None:
    raise RuntimeError("Project root could not be found.")

project_root = str(PROJECT_ROOT)
if project_root not in sys.path:
    sys.path.insert(0, project_root)

from Experiment.src.utils.pipeline import Pipeline

## 1. Initialize the pipeline

This loads and preprocesses the configured datasets once. Models are loaded lazily when a pipeline is selected.

In [2]:
pipeline = Pipeline()

Dataset: HotPotQA Initialized!
Dataset: Musique Initialized!
Dataset: TwoWikiMultihopQA Initialized!
Dataset: MultiHopRAG Initialized!
Dataset Constructor Initialized!

## 2. Inspect and validate the datasets

In [5]:
fields = pipeline.dataset_constructor.OUTPUT_FIELDS

for dataset_name, dataset in pipeline.dataset_constructor.datasets.items():
    print(f"\n=== {dataset_name} ===")
    print(f"train rows: {len(dataset.train_ds['query']):,}")
    print(f"val rows  : {len(dataset.val_ds['query']):,}")
    print(f"eval rows : {len(dataset.eval_ds['query']):,}")

    for split_name, split in (
        ("train", dataset.train_ds),
        ("validation", dataset.val_ds),
        ("eval", dataset.eval_ds),
    ):
        field_lengths = {field: len(split[field]) for field in fields}
        if len(set(field_lengths.values())) != 1:
            raise ValueError(
                f"Misaligned fields in {dataset_name}/{split_name}: {field_lengths}"
            )

    context_counts = Counter(
        len(gold) + len(distractors)
        for gold, distractors in zip(
            dataset.train_ds["gold_context"],
            dataset.train_ds["distractor"],
        )
    )
    print("train contexts per question:", dict(sorted(context_counts.items())))

print("\nAll dataset fields are aligned.")

=== hotpotqa/hotpot_qa ===
train rows: 3,000
val rows  : 150
eval rows : 1,000
train contexts per question: {3: 3, 4: 1, 5: 2996}

=== awinml/musique ===
train rows: 2,500
val rows  : 125
eval rows : 500
train contexts per question: {5: 2500}

=== framolfese/2WikiMultihopQA ===
train rows: 2,500
val rows  : 125
eval rows : 500
train contexts per question: {5: 2500}

=== yixuantt/MultiHopRAG ===
train rows: 2,000
val rows  : 50
eval rows : 500
train contexts per question: {5: 2000}

All dataset fields are aligned.

In [4]:
for dataset_name, dataset in pipeline.dataset_constructor.datasets.items():
    sample = {
        "query": dataset.train_ds["query"][0],
        "answer": dataset.train_ds["answer"][0],
        "gold_context": dataset.train_ds["gold_context"][0],
        "distractor": dataset.train_ds["distractor"][0],
    }
    print(f"\n=== Sample: {dataset_name} ===")
    pprint(sample, width=120)

=== Sample: hotpotqa/hotpot_qa ===
{'answer': '12 member universities',
 'distractor': ['Connecticut posted a 20–3 record, earned the Yankee Conference championship with a 10–0 regular '
                'season to claim the automatic bid to the 1959 NCAA University Division Baseball Tournament.\n'
                '\n'
                ' They were an automatic selection to the 1959 College World Series for District 1, their second '
                'appearance in the ultimate college baseball event.\n'
                '\n'
                ' The Huskies lost their first game against <a href="">Penn State\n'
                '\n'
                'The Washington Huskies baseball team is the varsity intercollegiate baseball team of the University '
                'of Washington, located in Seattle, Washington, United States.\n'
                '\n'
                ' The program has been a member of the NCAA Division I Pac-12 Conference since the start of the 1960 '
                'season, preceded by the Pacific Coast Conference.\n'
                '\n'
                ' The team has played at Husky Ballpark since 1998; the on-campus venue was renovated extensively for '
                'the start of the 2014 season.\n'
                '\n'
                " Lindsay Meggs has been the program's head coach since the start of the 2010 season.\n"
                '\n'
                ' The program has appeared in nine NCAA Tournaments.',
                'The program has appeared in nine NCAA Tournaments.\n'
                '\n'
                ' It has won two Pac-10 North-South Division Playoffs, six Pac-10 North Division Titles, eight PCC '
                'North Division Titles, and two PCC Regular Season Championships.\n'
                '\n'
                ' As of the start of the 2014 season, 18 former Huskies have appeared in the major leagues.\n'
                '\n'
                'The 1979 Connecticut Huskies baseball team represented the University of Connecticut in the 1979 NCAA '
                'Division I baseball season.\n'
                '\n'
                ' The Huskies were led by Larry Panciera in his 18th and final year as head coach, and played as part '
                'of the Eastern College Athletic Conference, a collection of northeastern universities with no other '
                'conference affiliation.\n'
                '\n'
                ' Connecticut posted a 31–13 record, won the ECAC, and reached the 1979 College World Series, their '
                'fifth appearance in the penultimate college baseball event.\n'
                '\n'
                ' The Huskies lost both games in the College World Series, being eliminated by eventual champion Cal '
                'State Fullerton.',
                'The following is a list of Connecticut Huskies baseball seasons.\n'
                '\n'
                ' The University of Connecticut is a member of the Big East Conference of the NCAA Division I.\n'
                '\n'
                ' The Huskies have made five College World Series appearances and seventeen appearances in the NCAA '
                'Division I Baseball Championship.\n'
                '\n'
                ' Conference records for the six seasons that the Huskies competed in the Eastern Collegiate Athletic '
                'Conference are not currently available.\n'
                '\n'
                'The 1965 Connecticut Huskies baseball team represented the University of Connecticut in the 1965 NCAA '
                'University Division baseball season.\n'
                '\n'
                ' The Huskies were led by Larry Panciera in his 4th year as head coach, and played as part of the '
                'Yankee Conference.\n'
                '\n'
                ' Connecticut posted a 16–9 record, earned a share of the Yankee Conference with a 7–3 regular season '
                'and won the automatic bid to the 1965 NCAA University Division Baseball Tournament with a playoff win '
                'over <a href="">Vermont'],
 'gold_context': ['The program is classified in the NCAA Division I, and the team competes in the American Athletic '
                  'Conference.\n'
                  '\n'
                  ' The team is coached by Jim Penders.\n'
                  '\n'
                  'J. O. Christian Field is a baseball stadium in Storrs, Connecticut, United States.\n'
                  '\n'
                  ' It is the home field of the Connecticut Huskies baseball team of the NCAA Division I American '
                  'Athletic Conference (The American).\n'
                  '\n'
                  ' The stadium holds 2,000 people.\n'
                  '\n'
                  ' It is named after former UConn baseball coach and athletic director, J. Orlean Christian.',
                  'The American Athletic Conference (also known as The American and sometimes abbreviated AAC) is an '
                  'American collegiate athletic conference, featuring 12 member universities and three associate '
                  "member universities that compete in the National Collegiate Athletic Association's (NCAA) Division "
                  'I, with its football teams competing in the Football Bowl Subdivision (FBS).\n'
                  '\n'
                  ' Member universities represent a range of private and public universities of various enrollment '
                  'sizes located primarily in urban metropolitan areas in the Northeastern, Midwestern, Western, and '
                  'Southern regions of the United States.\n'
                  '\n'
                  'The 1959 Connecticut Huskies baseball team represented the University of Connecticut in the 1959 '
                  'NCAA University Division baseball season.\n'
                  '\n'
                  ' The Huskies were led by J. O. Christian in his 24th year as head coach, and played as part of the '
                  'Yankee Conference.'],
 'query': 'How many member universities are there in this conference of which the Connecticut Huskies baseball team is '
          'a competing member?'}

=== Sample: awinml/musique ===
{'answer': 'Los Angeles County',
 'distractor': ['26 October Barracks is a former barracks of the Slovenian Armed Forces, located at Stara Vrhnika in '
                'Vrhnika Municipality, central Slovenia. It falls under the 25th military-territorial Vrhnika '
                'Slovenian Armed Forces Command.\n'
                '\n'
                'The ZEC Bras-Coupé-Desert is a "zone d\'exploitation contrôlée" (controlled harvesting zone) (ZEC), '
                'located in the unorganized territory of Lac-Pythonga in La Vallée-de-la-Gatineau Regional County '
                'Municipality, in the administrative region of Outaouais, in Quebec, in Canada.\n'
                '\n'
                'Ap Lo Chun () is a small island in the New Territories of Hong Kong. It is located in Ap Chau Bay () '
                'between Ap Chau in the east and Sai Ap Chau in the west, with the islet of Ap Tan Pai nearby in the '
                'northeast. It is under the administration of North District.',
                'Vilnius County () is the largest of the 10 counties of Lithuania, located in the east of the country '
                'around the city Vilnius. On 1 July 2010, the county administration was abolished, and since that '
                'date, Vilnius County remains as the territorial and statistical unit.\n'
                '\n'
                'Dallol is one of the woredas in the Afar Region of Ethiopia. This woreda is named for the former '
                'mining settlement of Dallol, which set the record for the hottest inhabited place on Earth, with an '
                'average temperature of 34° C. Located at the northernmost point of the Administrative Zone 2, '
                "Dallol's territory includes part of the Afar Depression. This woreda is bordered on the south by "
                'Koneba, on the west by the Tigray Region, on the north by Eritrea, and on the east and south by '
                'Berhale. Detailed information is not available for the settlements in this woreda.',
                'British Togoland, officially the Mandate Territory of Togoland and later officially the Trust '
                'Territory of Togoland, was a territory in West Africa, under the administration of the United '
                'Kingdom. It was effectively formed in 1916 by the splitting of the German protectorate of Togoland '
                'into two territories, French Togoland and British Togoland, during the First World War. Initially, it '
                'was a League of Nations Class B mandate. In 1922, British Togoland was formally placed under British '
                'rule while French Togoland, now Togo, was placed under French rule.\n'
                '\n'
                'The Arrondissement of Mechelen (; ) is one of the three administrative arrondissements in the '
                'Province of Antwerp, Belgium. It is both an administrative and a judicial arrondissement, as the '
                'territory for both coincides.'],
 'gold_context': ['John Harold Force (born May 4, 1949 in Bell Gardens, California) is an American NHRA drag racer. He '
                  'is a 16-time Funny Car champion driver and a 20-time champion car owner. Force owns and drives for '
                  'John Force Racing (JFR). He is one of the most dominant drag racers in the sport with 149 career '
                  'victories. He graduated from Bell Gardens High School and briefly attended Cerritos Junior College '
                  'to play football. He is the father of drag racers Ashley Force Hood, Brittany Force, and Courtney '
                  'Force. His oldest daughter Adria Hight is the CFO of JFR.',
                  'Bell Gardens is a city in Los Angeles County, California. The population was 42,072 at the 2010 '
                  'census, down from 44,054 at the 2000 census. Bell Gardens is part of the Gateway Cities Region, or '
                  'Southeast Los Angeles County (also shortened to SELA), a largely urbanized region located in '
                  'southeastern Los Angeles County between the City of Los Angeles, Orange County, and the Pacific '
                  'Ocean.\n'
                  '\n'
                  'Bogotá (/ ˈboʊɡətɑː /, / ˌbɒɡəˈtɑː /, / ˌboʊ - /; Spanish pronunciation: (boɣoˈta) (listen)), '
                  'officially Bogotá, Distrito Capital, abbreviated Bogotá, D.C., and formerly known as Santafé de '
                  'Bogotá between 1991 and 2000, is the capital and largest city of Colombia, administered as the '
                  'Capital District, although often thought of as part of Cundinamarca. Bogotá is a territorial entity '
                  'of the first order, with the same administrative status as the departments of Colombia. It is the '
                  'political, economic, administrative, industrial, artistic, cultural, and sports center of the '
                  'country.'],
 'query': 'What county contains the city where John Force was born?'}

=== Sample: framolfese/2WikiMultihopQA ===
{'answer': 'Pacific Palisades',
 'distractor': ['"This Is Murder" (4/9/66), portrayed by Gila Golan.\n'
                '\n'
                'Shortly after the release of this film, Cary Grant went into a self-imposed retirement from acting, '
                'turning down many film offers such as "Sabrina", in which he would have co-starred with Audrey '
                'Hepburn and "A Star Is Born" with Judy Garland.\n'
                '\n'
                'In 1955, director Alfred Hitchcock persuaded Grant to return to films with "To Catch a Thief".\n'
                '\n'
                'Bert Grund( 1920–1992) was a German composer of film scores.\n'
                '\n'
                'Walter Ulfig was a German composer of film scores.\n'
                '\n'
                'Henri Verdun( 1895–1977) was a French composer of film scores.\n'
                '\n'
                'Thomas Morse( born June 30, 1968) is an American composer of film and concert music.\n'
                '\n'
                'Alonso Mudarra( c. 1510 – April 1, 1580) was a Spanish composer of the Renaissance, and also played '
                'the vihuela, a guitar- shaped string instrument.\n'
                '\n'
                'He was an innovative composer of instrumental music as well as songs, and was the composer of the '
                'earliest surviving music for the guitar.',
                'Henri Verdun( 1895–1977) was a French composer of film scores.',
                'It was directed by Sidney Sheldon and produced by Dore Schary, from a screenplay by Herbert Baker, '
                'Alfred Lewis Levitt and Sidney Sheldon.'],
 'gold_context': ['Dream Wife is a 1953 romantic comedy film starring Cary Grant and Deborah Kerr made by '
                  'Metro-Goldwyn-Mayer.\n'
                  '\n'
                  'It was directed by Sidney Sheldon and produced by Dore Schary, from a screenplay by Herbert Baker, '
                  'Alfred Lewis Levitt and Sidney Sheldon.\n'
                  '\n'
                  'The music score was by Conrad Salinger, the cinematography by Milton R. Krasner and the art '
                  'direction by Daniel B. Cathcart and Cedric Gibbons.\n'
                  '\n'
                  'The costume design by Herschel McCoy and Helen Rose received an Oscar nomination.\n'
                  '\n'
                  "The film's secondary stars included Walter Pidgeon and Betta St. John, with supporting performances "
                  'by Eduard Franz, Buddy Baer, Richard Anderson, Dan Tobin, Dean Miller, and Movita.\n'
                  '\n'
                  'The character of Princess Tarji was resurrected in one episode of Sheldon\'s "I Dream of Jeannie", '
                  'titled\n'
                  '\n'
                  '"This Is Murder" (4/9/66), portrayed by Gila Golan.',
                  'Conrad Salinger (August 30, 1901, Brookline, Massachusetts – June 17, 1962, Pacific Palisades, '
                  'California) was an American arranger, orchestrator and composer, who studied classical composition '
                  'at the Paris Conservatoire.\n'
                  '\n'
                  'He is credited with orchestrating nine productions on Broadway from 1931 to 1938, and over '
                  'seventy-five motion pictures from 1931 to 1962.\n'
                  '\n'
                  'Film scholar Clive Hirschhorn considers him the finest orchestrator ever to work in the movies.\n'
                  '\n'
                  'Early in his career, film composer John Williams spent much time around Salinger.\n'
                  '\n'
                  'Amedeo Escobar( 1888–1973) was an Italian composer of film scores.\n'
                  '\n'
                  'Tarcisio Fusco was an Italian composer of film scores.\n'
                  '\n'
                  'He was the brother of the composer Giovanni Fusco and the uncle of operatic soprano Cecilia Fusco.\n'
                  '\n'
                  'Abe Meyer( 1901 – 1969) was an American composer of film scores.'],
 'query': 'Where was the place of death of the composer of film Dream Wife?'}

=== Sample: yixuantt/MultiHopRAG ===
{'answer': 'no',
 'distractor': ["Lionel Messi's arrival at Inter Miami has brought with it a craze for fans to get a glimpse of one of "
                "the sport's most talented and legendary players of all time.",
                '“We make Google be the default search engine,” he said, “because we’ve always thought it was the '
                'best.',
                'In our last roundup, we learned how Google spent $26.3 billion in 2021 making itself the default '
                'search engine across platforms and how Google tried to have Chrome preinstalled on iPhones.',
                '"We need to continue our investments to find a vaccine, to find a cure," she told Live Science.'],
 'gold_context': ['Erik ten Hag is a top coach from Ajax but they need a top blueprint not only for now but for the '
                  'next five years, and work towards that, and sometimes on that journey there are hard moments when '
                  "you don't get the right results, even though you're doing the right things.\n"
                  '\n'
                  'Manchester United are out of Europe altogether after a limp display against Bayern at Old Trafford, '
                  "where Kingsley Coman sealed a 1-0 win for Thomas Tuchel's side."],
 'query': 'Does the TalkSport article suggest that Manchester United does not need a long-term blueprint for success, '
          'while the Sporting News article indicates that Manchester United are out of European competitions, thus '
          'comparing the future planning with the current competition status of the team?'}

## 3. Prepare and train the HyperNet models

Each method receives the shared datasets. Training and validation contexts/queries are embedded and tokenized before training.

### 3.1 Type_MeanEmbeddings

In [ ]:
mean_pipeline = pipeline.use_embd2adapter("mean_embds")
mean_pipeline.hypernet_trainer.prepare_datasets()

print(f"MeanEmbeddings train rows: {len(mean_pipeline.hypernet_trainer.train_ds):,}")
print(f"MeanEmbeddings val rows:   {len(mean_pipeline.hypernet_trainer.val_ds):,}")

Embedding training contexts:   0%|          | 0/391 [00:00<?, ?batch/s]

Saved training embeddings to C:\Atelier\Research\Embd2Adapter_for_RAG\Notebooks\outputs\cache\embeddings_cache.npy

Embedding training queries:   0%|          | 0/79 [00:00<?, ?batch/s]

Saved training query embeddings to C:\Atelier\Research\Embd2Adapter_for_RAG\Notebooks\outputs\cache\embeddings_cache_queries.npy

Parameter 'function'=<function HyperNetTrainer.tokenize.<locals>.tokenize_batch at 0x000001C1CE2F6770> of the transform datasets.arrow_dataset.Dataset._map_single couldn't be hashed properly, a random hash was used instead. Make sure your transforms and parameters are serializable with pickle or dill for the dataset fingerprinting and caching to work. If you reuse this transform, the caching mechanism will consider it to be different from the previous calls and recompute everything. This warning is only shown once. Subsequent hashing failures won't be shown.

Tokenizing training dataset:   0%|          | 0/10000 [00:00<?, ? examples/s]

Training tokenization truncation stats:
  total_rows: 10000
  truncated_rows: 0
  truncated_ratio: 0.0
  max_raw_sequence_length: 1776
  total_removed_tokens: 0
  max_removed_tokens: 0

Embedding validation contexts:   0%|          | 0/18 [00:00<?, ?batch/s]

Saved validation embeddings to C:\Atelier\Research\Embd2Adapter_for_RAG\Notebooks\outputs\cache\embeddings_cache_validation.npy

Embedding validation queries:   0%|          | 0/4 [00:00<?, ?batch/s]

Saved validation query embeddings to C:\Atelier\Research\Embd2Adapter_for_RAG\Notebooks\outputs\cache\embeddings_cache_validation_queries.npy

Tokenizing validation dataset:   0%|          | 0/450 [00:00<?, ? examples/s]

Validation tokenization truncation stats:
  total_rows: 450
  truncated_rows: 0
  truncated_ratio: 0.0
  max_raw_sequence_length: 1409
  total_removed_tokens: 0
  max_removed_tokens: 0
MeanEmbeddings train rows: 10,000
MeanEmbeddings val rows:   450

In [7]:
mean_log_history, mean_hypernet_spec = mean_pipeline.train()
mean_hypernet_spec

[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 128009, 'pad_token_id': 128009}.

Embedding model unloaded: bge-m3:latest

[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer TokenizersBackend. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[transformers] There were missing keys in the checkpoint model loaded: ['lm_head.weight'].

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Parameters: 78,120,320
Trainable:  78,120,320
Size:       149.00 MiB
Training history appended to C:\Atelier\Research\Embd2Adapter_for_RAG\Experiment\Result\experiment_2026_08_13.json

{'num_parameters': 78120320,
 'trainable_parameters': 78120320,
 'parameter_size_bytes': 156240640,
 'parameter_size_mib': 149.002685546875}

### 3.2 Type_QueryDiffPooling

Projected context embeddings are normalized before self-attention and reused as its residual, while the projected query is independently normalized to the same scale. Their difference is passed through `diff_projector`; mean and max pooling are then concatenated and projected into the Controller input. The entire HyperNet is trained end-to-end using only the answer-label causal-LM loss.

In [ ]:
query_diff_pipeline = pipeline.use_embd2adapter("query_diff_pooling")
query_diff_pipeline.hypernet_trainer.prepare_datasets()

print(f"QueryDiffPooling train rows: {len(query_diff_pipeline.hypernet_trainer.train_ds):,}")
print(f"QueryDiffPooling val rows:   {len(query_diff_pipeline.hypernet_trainer.val_ds):,}")

VectorStore Initialized
Embd2Adapter Pipline Initialized!
Experiment Setup Completed. check the datasets whether it is correct or not, and begin training your model.

Loading weights:   0%|          | 0/254 [00:00<?, ?it/s]

HyperNetQueryDiffPoolingTrainer Initialized!
Hypernet with QueryDiffPooling Loaded.
Loaded training embeddings from C:\Atelier\Research\Embd2Adapter_for_RAG\Notebooks\outputs\cache\embeddings_cache.npy
Loaded training query embeddings from C:\Atelier\Research\Embd2Adapter_for_RAG\Notebooks\outputs\cache\embeddings_cache_queries.npy

Parameter 'function'=<function HyperNetTrainer.tokenize.<locals>.tokenize_batch at 0x000001BF01E616F0> of the transform datasets.arrow_dataset.Dataset._map_single couldn't be hashed properly, a random hash was used instead. Make sure your transforms and parameters are serializable with pickle or dill for the dataset fingerprinting and caching to work. If you reuse this transform, the caching mechanism will consider it to be different from the previous calls and recompute everything. This warning is only shown once. Subsequent hashing failures won't be shown.

Tokenizing training dataset:   0%|          | 0/10000 [00:00<?, ? examples/s]

Training tokenization truncation stats:
  total_rows: 10000
  truncated_rows: 0
  truncated_ratio: 0.0
  max_raw_sequence_length: 1776
  total_removed_tokens: 0
  max_removed_tokens: 0
Loaded validation embeddings from C:\Atelier\Research\Embd2Adapter_for_RAG\Notebooks\outputs\cache\embeddings_cache_validation.npy
Loaded validation query embeddings from C:\Atelier\Research\Embd2Adapter_for_RAG\Notebooks\outputs\cache\embeddings_cache_validation_queries.npy

Tokenizing validation dataset:   0%|          | 0/450 [00:00<?, ? examples/s]

Validation tokenization truncation stats:
  total_rows: 450
  truncated_rows: 0
  truncated_ratio: 0.0
  max_raw_sequence_length: 1409
  total_removed_tokens: 0
  max_removed_tokens: 0
QueryDiffPooling train rows: 10,000
QueryDiffPooling val rows:   450

In [7]:
query_diff_log_history, query_diff_hypernet_spec = query_diff_pipeline.train()
query_diff_hypernet_spec

[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 128009, 'pad_token_id': 128009}.

Embedding model unloaded: bge-m3:latest

[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer TokenizersBackend. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[transformers] There were missing keys in the checkpoint model loaded: ['lm_head.weight'].

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Parameters: 85,474,176
Trainable:  85,474,176
Size:       163.03 MiB
Training history appended to C:\Atelier\Research\Embd2Adapter_for_RAG\Experiment\Result\experiment_2026_08_15.json

{'num_parameters': 85474176,
 'trainable_parameters': 85474176,
 'parameter_size_bytes': 170948352,
 'parameter_size_mib': 163.029052734375}

## 4. Load and evaluate the trained models

Load the saved HyperNet parameters, then evaluate the complete evaluation split.

### 4.1 MeanEmbeddings

In [ ]:
mean_pipeline = pipeline.use_embd2adapter("mean_embds")
mean_checkpoint = mean_pipeline.load_trained_hypernet()
mean_results = mean_pipeline.experimentHyperNet()
mean_results

Loading weights:   0%|          | 0/254 [00:00<?, ?it/s]

HyperNetMeanEmbdsTrainer Initialized!
Hypernet with MeanEmbds Loaded.
Loaded trained HyperNet from outputs\mean_embds\hypernet_state_dict.pt

Evaluating hotpotqa/hotpot_qa (RAG):   0%|          | 0/1000 [00:00<?, ?question/s]

Evaluation Process Initialized
Result appended to C:\Atelier\Research\Embd2Adapter_for_RAG\Experiment\Result\experiment_2026_08_13.json

Evaluating hotpotqa/hotpot_qa (No RAG):   0%|          | 0/1000 [00:00<?, ?question/s]

Evaluation Process Initialized
Result appended to C:\Atelier\Research\Embd2Adapter_for_RAG\Experiment\Result\experiment_2026_08_13.json

Evaluating yixuantt/MultiHopRAG (RAG):   0%|          | 0/500 [00:00<?, ?question/s]

Evaluation Process Initialized
Result appended to C:\Atelier\Research\Embd2Adapter_for_RAG\Experiment\Result\experiment_2026_08_13.json

Evaluating yixuantt/MultiHopRAG (No RAG):   0%|          | 0/500 [00:00<?, ?question/s]

Evaluation Process Initialized
Result appended to C:\Atelier\Research\Embd2Adapter_for_RAG\Experiment\Result\experiment_2026_08_13.json

Evaluating awinml/musique (RAG):   0%|          | 0/500 [00:00<?, ?question/s]

Evaluation Process Initialized
Result appended to C:\Atelier\Research\Embd2Adapter_for_RAG\Experiment\Result\experiment_2026_08_13.json

Evaluating awinml/musique (No RAG):   0%|          | 0/500 [00:00<?, ?question/s]

Evaluation Process Initialized
Result appended to C:\Atelier\Research\Embd2Adapter_for_RAG\Experiment\Result\experiment_2026_08_13.json

Evaluating framolfese/2WikiMultihopQA (RAG):   0%|          | 0/500 [00:00<?, ?question/s]

Evaluation Process Initialized
Result appended to C:\Atelier\Research\Embd2Adapter_for_RAG\Experiment\Result\experiment_2026_08_13.json

Evaluating framolfese/2WikiMultihopQA (No RAG):   0%|          | 0/500 [00:00<?, ?question/s]

Evaluation Process Initialized
Result appended to C:\Atelier\Research\Embd2Adapter_for_RAG\Experiment\Result\experiment_2026_08_13.json

{'hotpotqa': {'rag': {'exact_match': 0.538, 'token_f1': 0.620357775736808},
  'no_rag': {'exact_match': 0.568, 'token_f1': 0.6540885036875749}},
 'multihoprag': {'rag': {'exact_match': 0.832, 'token_f1': 0.8466},
  'no_rag': {'exact_match': 0.834, 'token_f1': 0.8473999999999999}},
 'musique': {'rag': {'exact_match': 0.402, 'token_f1': 0.43980687704108756},
  'no_rag': {'exact_match': 0.618, 'token_f1': 0.6601040793296831}},
 '2wikimultihop': {'rag': {'exact_match': 0.646,
   'token_f1': 0.6715839105339105},
  'no_rag': {'exact_match': 0.672, 'token_f1': 0.6979496392496393}}}

### 4.2 QueryDiffPooling

In [4]:
query_diff_pipeline = pipeline.use_embd2adapter("query_diff_pooling")
query_diff_checkpoint = query_diff_pipeline.load_trained_hypernet()
query_diff_results = pipeline.experimentHyperNet()
query_diff_results

VectorStore Initialized
Embd2Adapter Pipline Initialized!
Experiment Setup Completed. check the datasets whether it is correct or not, and begin training your model.

Loading weights:   0%|          | 0/254 [00:00<?, ?it/s]

HyperNetQueryDiffPoolingTrainer Initialized!
Hypernet with QueryDiffPooling Loaded.
Loaded trained HyperNet from outputs\query_diff_pooling\hypernet_state_dict.pt

Evaluating hotpotqa/hotpot_qa (RAG):   0%|          | 0/1000 [00:00<?, ?question/s]

[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer TokenizersBackend. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.

Evaluation Process Initialized
Result appended to C:\Atelier\Research\Embd2Adapter_for_RAG\Experiment\Result\experiment_2026_08_15.json

Evaluating hotpotqa/hotpot_qa (No RAG):   0%|          | 0/1000 [00:00<?, ?question/s]

Evaluation Process Initialized
Result appended to C:\Atelier\Research\Embd2Adapter_for_RAG\Experiment\Result\experiment_2026_08_15.json

Evaluating yixuantt/MultiHopRAG (RAG):   0%|          | 0/500 [00:00<?, ?question/s]

Evaluation Process Initialized
Result appended to C:\Atelier\Research\Embd2Adapter_for_RAG\Experiment\Result\experiment_2026_08_15.json

Evaluating yixuantt/MultiHopRAG (No RAG):   0%|          | 0/500 [00:00<?, ?question/s]

Evaluation Process Initialized
Result appended to C:\Atelier\Research\Embd2Adapter_for_RAG\Experiment\Result\experiment_2026_08_15.json

Evaluating awinml/musique (RAG):   0%|          | 0/500 [00:00<?, ?question/s]

Evaluation Process Initialized
Result appended to C:\Atelier\Research\Embd2Adapter_for_RAG\Experiment\Result\experiment_2026_08_15.json

Evaluating awinml/musique (No RAG):   0%|          | 0/500 [00:00<?, ?question/s]

Evaluation Process Initialized
Result appended to C:\Atelier\Research\Embd2Adapter_for_RAG\Experiment\Result\experiment_2026_08_15.json

Evaluating framolfese/2WikiMultihopQA (RAG):   0%|          | 0/500 [00:00<?, ?question/s]

Evaluation Process Initialized
Result appended to C:\Atelier\Research\Embd2Adapter_for_RAG\Experiment\Result\experiment_2026_08_15.json

Evaluating framolfese/2WikiMultihopQA (No RAG):   0%|          | 0/500 [00:00<?, ?question/s]

Evaluation Process Initialized
Result appended to C:\Atelier\Research\Embd2Adapter_for_RAG\Experiment\Result\experiment_2026_08_15.json

{'hotpotqa': {'rag': {'exact_match': 0.548, 'token_f1': 0.625139297630474},
  'no_rag': {'exact_match': 0.585, 'token_f1': 0.6616658774031839}},
 'multihoprag': {'rag': {'exact_match': 0.888, 'token_f1': 0.8975333333333333},
  'no_rag': {'exact_match': 0.872, 'token_f1': 0.8815333333333333}},
 'musique': {'rag': {'exact_match': 0.408, 'token_f1': 0.4535345044429255},
  'no_rag': {'exact_match': 0.618, 'token_f1': 0.6413779337105963}},
 '2wikimultihop': {'rag': {'exact_match': 0.636,
   'token_f1': 0.662062481962482},
  'no_rag': {'exact_match': 0.648, 'token_f1': 0.6724529581529581}}}

### 4.3 BaseModel

In [4]:
# Release the active HyperNet before loading the BaseModel pipeline.
#query_diff_pipeline.release_method()
base_pipeline = pipeline.use_base_model()
base_results = base_pipeline.experimentBaseModel()
base_results

Evaluating hotpotqa/hotpot_qa (RAG):   0%|          | 0/1000 [00:00<?, ?question/s]

Evaluation Process Initialized
Result appended to C:\Atelier\Research\Embd2Adapter_for_RAG\Experiment\Result\experiment_2026_08_15.json

Evaluating hotpotqa/hotpot_qa (No RAG):   0%|          | 0/1000 [00:00<?, ?question/s]

Evaluation Process Initialized
Result appended to C:\Atelier\Research\Embd2Adapter_for_RAG\Experiment\Result\experiment_2026_08_15.json

Evaluating yixuantt/MultiHopRAG (RAG):   0%|          | 0/500 [00:00<?, ?question/s]

Evaluation Process Initialized
Result appended to C:\Atelier\Research\Embd2Adapter_for_RAG\Experiment\Result\experiment_2026_08_15.json

Evaluating yixuantt/MultiHopRAG (No RAG):   0%|          | 0/500 [00:00<?, ?question/s]

Evaluation Process Initialized
Result appended to C:\Atelier\Research\Embd2Adapter_for_RAG\Experiment\Result\experiment_2026_08_15.json

Evaluating awinml/musique (RAG):   0%|          | 0/500 [00:00<?, ?question/s]

Evaluation Process Initialized
Result appended to C:\Atelier\Research\Embd2Adapter_for_RAG\Experiment\Result\experiment_2026_08_15.json

Evaluating awinml/musique (No RAG):   0%|          | 0/500 [00:00<?, ?question/s]

Evaluation Process Initialized
Result appended to C:\Atelier\Research\Embd2Adapter_for_RAG\Experiment\Result\experiment_2026_08_15.json

Evaluating framolfese/2WikiMultihopQA (RAG):   0%|          | 0/500 [00:00<?, ?question/s]

Evaluation Process Initialized
Result appended to C:\Atelier\Research\Embd2Adapter_for_RAG\Experiment\Result\experiment_2026_08_15.json

Evaluating framolfese/2WikiMultihopQA (No RAG):   0%|          | 0/500 [00:00<?, ?question/s]

Evaluation Process Initialized
Result appended to C:\Atelier\Research\Embd2Adapter_for_RAG\Experiment\Result\experiment_2026_08_15.json

{'hotpotqa': {'rag': {'exact_match': 0.448, 'token_f1': 0.3208403041318227},
  'no_rag': {'exact_match': 0.472, 'token_f1': 0.3449720178769288}},
 'multihoprag': {'rag': {'exact_match': 0.444, 'token_f1': 0.3521111111111111},
  'no_rag': {'exact_match': 0.454, 'token_f1': 0.3450779220779221}},
 'musique': {'rag': {'exact_match': 0.102, 'token_f1': 0.07544919242941546},
  'no_rag': {'exact_match': 0.162, 'token_f1': 0.10449382691190424}},
 '2wikimultihop': {'rag': {'exact_match': 0.228,
   'token_f1': 0.1766447002267772},
  'no_rag': {'exact_match': 0.244, 'token_f1': 0.1986058235355422}}}